export const microsoftSkills = [
  "Python",
  ".NET",
  "Java",
  "JavaScript",
  "Azure",
  "Microsoft",
  "Power Apps",
  "Power Platform",
  "Dynamics",
  "M365",
  "GitHub",
  "Fabric",
  "Synapse",
  "C#",
  "C++",
  "Go",
  "TypeScript",
  "React",
  "Angular",
  "Node.js",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Docker",
  "Kubernetes",
  "Git",
  "Jenkins",
  "CI/CD",
  "Azure DevOps",
  "Agile",
  "Serverless",
  "Microservices",
  "RESTful APIs",
  "GraphQL",
  "NoSQL",
  "Redis",
  "Dynamics 365",
  "Power BI",
  "Power Automate",
  "Power Virtual Agents",
  "Microsoft Fabric",
  "Azure Synapse",
];

export const searchSkills = [
  // "Python",
  // ".NET",
  // "Azure",
  // "Microsoft",
  // "Power Apps",
  // "Power Platform",
  // "Dynamics",
  // "M365",
  // "Synapse",
  // "Azure Devops",
  // "Dynamics 365",
  // "Power BI",
  // "Power Automate",
  // "Microsoft Fabric",
  // "Azure Synapse",
  "Fabric",
  "Synapse",
  "Copilot Studio",
  "AKS",
  "Azure AI",
  "Dynamics",
  "Sentinel",
  "Power BI",
  "Azure DevOps",
  "GitHub",
  "AVS",
  "M365",
  "Sharepoint",
  "SQL Server"
];

export const blogCategories = [
  "Business Applications",
  "Data and AI",
  "Security",
  "Digital and Application Innovation",
  "Infrastructure",
  "Modern Work",
  "Account Executive",
  "Alliance",
];

export const keywords = [
  "power platform",
  "dynamics",
  "m365",
  "microsoft fabric",
  "azure synapse",
  "power bi",
];

export const PAGES = 50;

export const PARTNER_PAGES = 10;
