export const microsoftSkills = [
    "Python",
    ".NET",
    "Java",
    "JavaScript",
    "Azure",
    "Power Apps",
    "Power Platform",
    "Dynamics",
    "M365",
    "GitHub",
    "Fabric",
    "Synapse",
    "C#",
    "C++",
    "Go",
    "TypeScript",
    "React",
    "Angular",
    "Node.js",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Docker",
    "Kubernetes",
    "Git",
    "Jenkins",
    "CI/CD",
    "Azure DevOps",
    "Agile",
    "Serverless",
    "Microservices",
    "RESTful APIs",
    "GraphQL",
    "NoSQL",
    "Redis",
    "Dynamics 365",
    "Power BI",
    "Power Automate",
    "Power Virtual Agents",
    "Microsoft Fabric",
    "Azure Synapse",
    "Power BI",
];
  
export const keywords = [
    "Active Directory Administrator",
    "AI/ML Data Scientist (Azure)",
    "Analyze and visualize data",
    "App Developer (Azure)",
    "AS Analytics",
    "ASP.NET Core",
    "ASP.NET",
    "Analytical Processing",
    "Azure administration",
    "Azure AI Engineer",
    "Azure Administrator",
    "Azure App Services Administrator",
    "Azure App Services Developer",
    "Azure Artifacts",
    "Azure Blob Storage",
    "Azure Boards",
    "Azure Cloud Services",
    "Azure Container Registry",
    "Azure Data Engineer",
    "Azure Data Factory",
    "Azure Data Lake",
    "Azure Data Scientist",
    "Azure Databricks",
    "Azure DDos Protection",
    "Azure DevOps",
    "Azure DevOps Engineer",
    "Azure development",
    "Azure Disk Encryption",
    "Azure ExpressRoute",
    "Azure Firewall",
    "Azure Firewall Specialist",
    "Azure Graph",
    "Azure Kubernetes Service (AKS)",
    "Azure Key Vault",
    "Azure Migration Framework",
    "Azure Pipelines",
    "Azure Repos",
    "Azure Sales Executive",
    "Azure Security Engineer",
    "Azure Security Operations Analyst",
    "Azure Service Adoption Specialist",
    "Azure Solution Architect",
    "Azure SQL Database",
    "Azure Stream",
    "Azure Synapse Analytics",
    "Azure Synapse Apache Spark Pools",
    "Azure Synapse serverless SQL pools",
    "Azure Technology Manager",
    "Azure Virtual Machines",
    "AZ-400",
    "BI Analyst (Fabric)",
    "BI Analyst (Power BI)",
    "business solutions",
    "Copilot Studio Solution Architect",
    "continuous integration",
    "Data Analytics Solutions",
    "Data Scientist (Azure)",
    "Data Storage Solutions",
    "Dataverse",
    "Design and manage business solutions",
    "Design Data Integration",
    "DevOps Architect (Azure)",
    "DevOps Consultant (Azure)",
    "DevOps processes",
    "Disaster Recovery",
    "D365 Business Central Functional Consultant",
    "D365 Customer Service Functional Consultant",
    "D365 Finance Functional Consultant",
    "D365 Sales Functional Consultant",
    "D365 Supply Chain Management Functional Consultant",
    "Dynamics 365",
    "Enterprise Architect (M365)",
    "Excel PivotTables",
    "GitHub",
    "Infrastructure administrator",
    "Junior Data Scientist (Azure)",
    "Microsoft 365 Architect",
    "Microsoft Account manager",
    "Microsoft Defender for Cloud",
    "Microsoft Enterprise account executive",
    "Microsoft Entra ID",
    "Microsoft Fabric Analyst",
    "Microsoft Graph",
    "Microsoft Sentinel",
    "ML Engineer (Azure)",
    "MLOps Specialist (Azure)",
    "Model-Driven Apps",
    "Network Administrator",
    "Office 365 Administrator",
    "Power Apps",
    "Power Apps Consultant",
    "Power Apps Developer",
    "Power Automate",
    "Power BI Analyst",
    "Power BI Consultant",
    "Power BI Developer",
    "Power platform Specialist",
    "Power Platform Architect",
    "Power Platform Consultant",
    "Power Platform Functional Consultant",
    "Principal Data Scientist (Azure)",
    "Secure network solutions",
    "Security Engineer",
    "Senior Data Scientist (Azure)",
    "SharePoint Administrator",
    "source control",
    "SQL Server",
    "Systems Administrator",
    "Technical Architect (M365)",
    "Technical Specialist (M365)",
    "Teams",
    "Visual Basic",
    "Web developer (Azure)",
    "Windows Server Administrator",
];

export const Query=Array.from(new Set([...microsoftSkills, ...keywords]));
  
export const cities = [
    "New York",
    "Washington D.C.",
    "San Francisco",
    "Plano",
    "Jersey City",
    "Atlanta",
    "Chicago",
    "Seattle",
    "Boston",
    "Austin",
    "Los Angeles",
    "Dallas",
    "Denver",
    "Charlotte",
    "San Jose",
    "Raleigh",
    "Minneapolis",
    "Houston",
    "Phoenix",
    "San Diego",
    "Irvine",
    "Philadelphia",
    "Portland",
    "Columbus",
    "Indianapolis",
    "Nashville",
    "Pittsburgh",
    "Salt Lake",
    "Miami",
    "Tampa",
    "Kansas",
    "St. Louis",
    "Orlando",
    "Detroit",
    "San Antonio",
    "Sacramento",
    "Las Vegas",
    "Baltimore",
    "Cincinnati",
    "Milwaukee",
    "Providence",
    "Hartford",
    "Richmond",
    "Louisville",
    "Albuquerque",
    "Oklahoma City",
    "Omaha",
    "Memphis",
    "Buffalo",
    "Birmingham",
    "Jacksonville",
    "New Orleans",
    "Virginia Beach",
    "Rochester",
    "El Paso",
    "Tucson",
    "Fresno",
    "Honolulu",
    "Boise",
    "Des Moines",
    "Little Rock",
    "Anchorage",
    "Wichita",
    "Spokane",
    "Tulsa",
    "Lexington",
    "Greensboro",
    "Durham",
    "Lubbock",
    "Baton Rouge",
    "Mobile",
    "Knoxville",
    "Dayton",
    "Charleston",
    "Syracuse",
    "Chattanooga",
    "Columbia",
    "Shreveport",
    "Fargo",
    "Sioux Falls",
    "Bozeman",
    "Burlington",
    "Billings",
    "Helena",
    "Juneau",
    "Cheyenne",
    "Dover",
    "Montgomery",
    "Pierre",
    "Concord",
    "Frankfort",
    "Carson City",
    "Santa Fe",
    "Augusta",
    "Montpelier",
];

export default {
    microsoftSkills,
    keywords,
    cities,
    Query,
}